/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "var(--on-primary-fixed)",
        "secondary": "var(--secondary)",
        "outline": "var(--outline)",
        "on-error": "var(--on-error)",
        "error": "var(--error)",
        "inverse-surface": "var(--inverse-surface)",
        "primary": "var(--primary)",
        "surface-variant": "var(--surface-variant)",
        "secondary-fixed": "var(--secondary-fixed)",
        "outline-variant": "var(--outline-variant)",
        "tertiary-container": "var(--tertiary-container)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "inverse-primary": "var(--inverse-primary)",
        "on-error-container": "var(--on-error-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface": "var(--surface)",
        "tertiary": "var(--tertiary)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-high": "var(--surface-container-high)",
        "background": "var(--background)",
        "on-tertiary": "var(--on-tertiary)",
        "secondary-container": "var(--secondary-container)",
        "on-primary": "var(--on-primary)",
        "on-surface": "var(--on-surface)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-background": "var(--on-background)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "primary-container": "var(--primary-container)",
        "surface-container": "var(--surface-container)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "surface-dim": "var(--surface-dim)",
        "primary-fixed": "var(--primary-fixed)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "surface-tint": "var(--surface-tint)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "error-container": "var(--error-container)",
        "on-secondary": "var(--on-secondary)",
        "on-primary-container": "var(--on-primary-container)",
        "surface-container-low": "var(--surface-container-low)",
        "steel-blue": "var(--steel-blue)",
        primaryOld: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        surfaceOld: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-compact": "4px",
        "container-max": "1200px",
        "stack-default": "16px",
        "editorial-margin": "64px",
        "gutter-grid": "1px"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        "metadata": ["JetBrains Mono"],
        "body-mono": ["JetBrains Mono"],
        "display-lg": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "abstract-serif": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "data-tabular": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"]
      },
      fontSize: {
        "metadata": ["11px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-mono": ["14px", { lineHeight: "1.5", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "abstract-serif": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "data-tabular": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }]
      },
      animation: {
        'march': 'march 1s linear infinite',
        'shimmer': 'shimmer 2s infinite linear',
        'pulse-glow': 'pulseGlow 2s infinite',
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
      },
      keyframes: {
        march: {
          '0%': { backgroundPosition: '0 0' },
          '100%': { backgroundPosition: '20px 0' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        pulseGlow: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: .5 },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
};
